language: java

jdk:
    - oraclejdk8
    
branches:
  only:
  - master

notifications:
    email:
      recipients:
        apalache-build@forsyte.at
      on_success: change
      on_failure: always

