language: java

jdk:
    - oraclejdk8

python:
    - "2.7"

os:
    - linux

# required to compile z3
addons:
  apt:
    packages:
    - gcc-4.7
    - g++-4.7

# locally compile z3 and make it available via LD_LIBRARY_PATH
before_install:
  - git clone https://github.com/Z3Prover/z3 ~/build/z3repo
  - mkdir ~/build/lib
  - pushd ~/build/z3repo
  - python scripts/mk_make.py --java -p ~/build/lib/
  - cd build
  - make
  - make install
  - export LD_LIBRARY_PATH=~/build/lib
  - popd
  - cp ~/build/lib/com.microsoft.z3.jar ~/3rdpartylib
  - pushd 3rdparty
  - ./install-local.sh
  - popd

branches:
  only:
  - master
  - unstable

notifications:
    email:
      recipients:
        apalache-build@forsyte.at
      on_success: change
      on_failure: always

