name: deploy

on:
  push:
    branches:
      - master
      # TODO Remove once deploying unstable versions separately
      - unstable
      - shon/emojify-docs

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.5"
          # mdbook-version: 'latest'

      - name: Use OCaml 4.11.0
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.11.0

      - name: Install emojitsu
        run: |
          opam pin https://github.com/shonfeder/emojitsu.git#0.0.5

      - name: Build the mdBook
        run: |
          cd docs
          # Emojify the markdown
          find . -type f -name "*.md" -exec opam exec -- emojitsu emojify -i {} \;
          # Build the book
          mdbook build
          # mdbook generates this file automatically but it breaks the gh-pages
          # jekyll rendering we use for the base site
          rm ../target/docs/.nojekyll

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./target/docs
      #     destination_dir: docs
      #     # We use GitHub's builtin jekyll for rendering the main landing page
      #     enable_jekyll: true
